### ISSUE TITLE
HTML is not parsed well on the "Tagline" setting

### ISSUE THREAD

**Issue by NedkoHristov** [andersnoren/wilson#1]
Using HTML tags (I've tried with <br> and <p>) from the Customizing -> Site Identity -> Tagline (see screenshot below).
When I use <br> the preview works well, but when I save it and refresh the front page of the blog the HTML is not being parsed.

![image](https://github.com/user-attachments/assets/2c4790ad-04e7-4310-bccb-f31c1d2d8886)
![image](https://github.com/user-attachments/assets/2af408cb-58a6-4bf0-b70e-2a0e5aedfe12)

**Comment by andersnoren** [comment]
Hi @NedkoHristov! 

WordPress doesn't parse HTML output with `get_bloginfo()`/`bloginfo()` by default, so Wilson doesn't either. You can filter `get_bloginfo()` with the `bloginfo` hook to format it as HTML in a child theme or in a plugin.

— Anders
